### ISSUE TITLE
[feat] parser 클래스 생성

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [CuteWebserv/webserv#12]
# Summary

클라이언트가 보낸 http request 정보를 저장하고, 유효한 정보가 담겨있는지 확인하는 `Parser` 클래스를 생성했습니다.

# Detail

## `Request` 구조체

http **response** 를 만들 때 확인할 `Request` 구조체를 생성했습니다.

```c++
struct Request {
  char* first_line;
  std::string method;
  std::string uri;
  std::string http_version;
  std::map<std::string, char*> header;
  std::vector<char> body;
  ErrorNum err_num; // 어떤 에러가 발생했는지 알려주는 Enum
}
```

## `RequestPool` 구조체

http **request** 를 저장하고 관리하기 위한 `RequestPool` 구조체를 생성했습니다.

```c++
struct RequestPool {
  char* total_line;
  size_t line_len;
  size_t prev_offset;
  size_t offset;
  bool found_newline;
}
```
- 위의 구조체에서 각 변수가 의미하는 것은 다음과 같습니다.
  - `total_line` : 클라이언트가 보낸 request 를 하나의 문자열로 저장하는 변수
  - `line_len` : `total_line` 문자열의 총 길이를 저장하는 변수
  - `prev_offset` : 마지막으로 CRLF(`\r\n`) 를 만난 인덱스를 저장하는 변수
  - `offset` : 새롭게 들어온 CRLF(`\r\n`) 를 만난 시점의 인덱스를 저장하는 변수
  - `found_newline` : 클라이언트가 보낸 패킷에 CRLF(`\r\n`)가 포함되어 있는지 확인하는 변수

## Todo

- [x] `Parser` 클래스 정의
- [x] `char*` 자료형을 쉽게 다루기 위한 C Style 함수 작성 in `utils.cpp`
  - [x] `ft_strlen`, `ft_strdup`, `ft_strjoin`
- [x] Makefile 작성
- [x] `first_line` 파싱하는 함수 작성
  - [x] 유효한 method 인지 확인
  - [x] 유효하지 않으면 `ErrorNum` 지정
- [x] `header` 파싱하는 함수 작성
- [x] `body` 파싱하는 함수 작성
  - [x] chunked body 인 경우에도 정상 작동 확인
