### ISSUE TITLE
[Feat] config 파일 파싱받기

### ISSUE THREAD

**Issue by Arkingco** [CuteWebserv/webserv#13]
## Desc
config 파일을 파싱 받고 서버 세팅을 config 파일에 맞게 맞추기

## Detail
config 파일의 형식은  서브젝트에 명시되어 있지 않아 json 파일 형식을 따라 작성 하려고함
config 파일에 있어야 하는 항목은 다음과 같음

### config 항목
- Server block: 이것은 특정 서버 또는 웹 사이트에 대한 기본 구성을 정의하며 "server" 블록 내에서 묶여 있습니다.
- Server name directive: 이것은 서버 블록이 응답해야 하는 도메인 이름 또는 IP 주소를 지정합니다. 예를 들어, "server_name example.com;"은 "example.com" 도메인 이름으로 요청을 처리합니다.
- Root directive: 이것은 웹 사이트 파일의 루트 디렉토리를 지정합니다. 예를 들어, "root /var/www/example.com;"은 "/var/www/example.com" 디렉토리에서 파일을 제공합니다.
- Index directive: 이것은 디렉토리가 요청되었을 때 기본 파일을 제공합니다. 예를 들어, "index index.html;"은 요청된 디렉토리에 "index.html" 파일이 있으면 해당 파일을 제공합니다.
- Location block: 이것은 서버 블록 내에서 특정 위치에 대한 구성을 정의합니다. 예를 들어, 위치 블록을 사용하여 다른 루트 디렉토리를 지정하거나 요청을 다른 서버로 프록시할 수 있습니다.

-- chat gpt answer -- 

## Todo

- [x] config 파일 인자가 있는지 확인 없으면 default 파일 불러오기
- [x] config 파일 파싱받기
    - [x] 전부 map container로 저장
- [x] #19
	- [x] 각 필수 구성 요소들이 존재 하는지 확인하기
	- Server block, Server name directive, Root directive, Index directive, Location block
	

## Etc
- std::string 탐색 함수 find()는 문자열이 있으면 문자열 시작 인덱스 없으면 std::string::npos를 리턴합니다
