### ISSUE TITLE
[Feat] test로 정상 작동을 점검하는 브랜치

### ISSUE THREAD

**Issue by ssolpang** [CuteWebserv/webserv#146]
## Desc

tester 외에 기본적인 테스트 케이스를 넣으며 정상 작동하는지 확인하기 위한 브랜치

## Todo

- [ ] 메서드 정상 작동 여부
- [ ] conf 파일에 따른 정상 작동 여부
- [ ] PUT, POST 확인

**Comment by ssolpang** [comment]
POST, PUT 메소드를 받을 때 Parser에서 멈추는 부분 해결 by joonhan
다른 브랜치에서 코드 해결했기에 issue close
