### ISSUE TITLE
[Feat] HTTP 파트에서 CGI를 처리 하는 handler 클래스 생성

### ISSUE THREAD

**Issue by ssolpang** [CuteWebserv/webserv#38]
## Desc

GET, POST, DELETE 메소드에서 CGI 처리하는 handler 클래스 생성

## Detail

클래스 이름(미정)

Request 데이터 분석 결과 php 파일 등 추가 CGI 프로그램 실행이 필요할 경우, 본 클래스로 넘겨짐.
해당 데이터를 CGI 프로그램에 넘겨 HTML 파일 형태로 가공 받음(== body 내용).
자식 프로세스를 통해 위의 과정을 수행 후 다시 본 (부모) 프로세스로 데이터를 받음.

MethodHandler 클래스를 이용한 처리 방식과의 일관성을 위해,
추상 클래스를 상속 받는 CGI ver. GET, POST, DELETE 처리 클래스 만들기.

우선 php-cgi만 테스트해볼 예정.

## Todo

- [ ] 클래스 이름 추천 받기(class CgiHandler,,)
- [x] 캐노니컬 폼 작성
- [x] php-cgi로 최소 기능 코드 구현(GET)
- [ ] php-cgi로 최소 기능 코드 구현(POST)
- [ ] php-cgi로 최소 기능 코드 구현(DELETE)

## Etc

joonhan님이 작성해주신 CGI 실행 코드 참고 예정
