### ISSUE TITLE
[Feat] kqueue_cgi 테스트

### ISSUE THREAD

**Issue by Arkingco** [CuteWebserv/webserv#46]
## Desc
kqueue_cgi 테스트 코드 구현

## Detail
- cgi 프로세스가 중료되는 분기는 크게 두 가지로 나뉜다.
   1. cgi 프로세스가 끝났을 때
   2. 너무 오랫동안 처리가 될때(TIME_OUT)
- 각각의 케이스를 처리하는 테스트 코드를 작성하기!

- kevent와 같은 경우 여러가지 이벤트 filter를 받을 수 있다.
- 가장 많이 사용되는 필터 이벤트
  - `EVFILT_READ`
  - `EVFILT_WRITE`
- 해당하는 이벤트들은 `kqueue event`가 실행 됐을 때 어떤 이벤트 `filter`에 걸려서 처리가 됐는지 구분할 수 있개 해주는 요소 들이다.
- 해당하는 fd에 READ를 할 수 있으면 `EVFILT_READ` WRITE를 할 수 있으면 `EVFILT_WRITE`와 같은 방식이다
- kqueue는 fd뿐만 아니라 프로세스의 상태도 캐치하여 이벤트를 발생시킬 수 있다.
	- filter `EVFILT_PROC` 와 fflag `NOTE_EXIT`는 프로세스가 종료 되었을 때의 이벤트를 캐치할 수 있어 이부분에서 CGI의 정상적 출력 처리를 받게 코드를 작성하려고 한다.
- 또한 `GCI`가 `너무 오랫동안` `실행`될 수 있음을 고려하여 `timer`를 만들어서 `특정 시간`동안 event가 `실행되지 않았다면` timer코드를 실행 시켜서 `프로세스를 종료`시키는 분기도 작성한다

## Todo

- [x] EVFIL_PROC를 활용하여 프로세스 종료 이벤트 캐치하기
- [X] 프로세스가 정상 종료 되었을 때 무한루프에 걸렸을 때 이벤트 분기 처리하기
- [x] 분기 처리에 맞게 이벤트를 삭제하기
	- 정상 종료
		- 타이머 삭제
		- `EVFIL_PROC` 이벤트 `자동` 삭제
	- 무한루프
		- 타이머 `자동` 삭제
		-  `EVFIL_PROC` 이벤트 삭제
