### ISSUE TITLE
[Fix] Config 내 수정사항 요청

### ISSUE THREAD

**Issue by Elineely** [CuteWebserv/webserv#47]
## Desc

HttpProcessor 내에서 MethodHandler 보다 먼저 호출되는 PathFinder에서 config 및 request에서 정보를 가져오는데, 이에따라 필요한 Config.hpp/cpp 에 수정 사항을 요청합니다.

## Detail

- 전부 추가후 따로 요청 드릴 예정!
- 현재는 잊어버리지 않게 메모용 이슈

## Todo

- [ ] server name 삭제 -> 포트 번호로 호스팅하는 사이트를 구분한다.
- [ ] http 단에서는 port 번호를 알수 없음.
![스크린샷 2023-05-25 오후 1 57 18](https://github.com/CuteWebserv/webserv/assets/80635378/a9a383bf-d25f-4ae2-aabc-1033b386c736)
현재 처리할 server block에 해당하는 t_server를 HttpProcessor에게 넘겨주어야함

- [ ] .config 파일 내, 동일 블록에서  지시어 중복 불가(한번 이상 나오면 서버 종료)로 변경
- [ ] root, index, location, ourcgi_pass, ourcgi_index 지시어 뒤 상위 폴더로 올라가는 "../" 나올수 없게 -> 나오면 오류 처리 (보안 목적)
- [ ] 환경변수 확장 가능 여부 -> '$'나오면 오류 처리 해도될듯 => \.php$는 제외? X cgi 블록 형식 지정을 다른 방식으로 하는게 좋을듯.
- [ ]  index 지시어 뒤 여러 argument 올수있게(2개이상) 처리, 저장해야함( location 내부에선 안됨)
```
server {
    server_name localhost
    listen 10005
    index kiparks_server server_kipark2
    location / {
        root Users/surinlee/Desktop/42/web_serv/src/HttpProcessor/PathTest/others
        index a
        index a b.php c.html
       //Error: non-vaild content in line: 8 --> 2개 이상 argument에서 에러남
    }
(...)
}
```
- [ ] server.conf 내 빈줄 있을 시 segmentation fault
```
server {
    server_name localhost
    listen 10005
    index kiparks_server server_kipark2
    location / {
        root Users/surinlee/Desktop/42/web_serv/src/HttpProcessor/PathTest/others
        index a
    }

}
```
![스크린샷 2023-05-24 오후 5 13 33](https://github.com/CuteWebserv/webserv/assets/80635378/6f025fdf-b10f-4d1e-abf5-4d21969d6b4e)

- [ ] 현재 다중 location 블록 불가
```
server {
    server_name localhost
    listen 10005
    index kiparks_server server_kipark2
    location / {
        root Users/surinlee/Desktop/42/web_serv/src/HttpProcessor/PathTest/others
        index a
    }
    location /admin{
        root ./others //Error: non-vaild content in line:
        index b
    }
}
```
