### ISSUE TITLE
[Feat] 파일 업로드 및 삭제 php 코드 작성

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [CuteWebserv/webserv#51]
## Desc

요구 사항 중에 파일 업로드를 구현하는 항목(`POST`)과 `DELETE` 메서드가 작동하도록 php 코드 내에서 구현합니다.

## Detail

- 파일 업로드 기능
- 사진 표시 기능
- 사진 삭제 기능

## Todo

- [x] 파일 업로드 기능
- [x] 사진 표시 기능
- [x] 사진 삭제 기능

## Etc

- 해당 기능 필요 여부에 따라 main 브랜치로 병합하거나 해당 이슈를 삭제할 예정입니다.
