### ISSUE TITLE
[Feat] log 출력용 클래스 생성

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [CuteWebserv/webserv#79]
## Desc

디버깅, 오류 발생, 서버 작동 상태를 확인하기 위해 출력문을 생성하는 클래스입니다. 

## Detail

- 오류가 발생한 경우 `[ERROR] message` 으로 표시합니다.
- 일반적인 목적으로 출력하는 경우에는 `[INFO] message` 으로 표시합니다.
- 디버깅 목적으로 출력하는 경우 `[DEBUG] message` 으로 표시합니다.

## Todo

- [x] Logger 클래스 생성
- [x] error 함수 생성
- [x] info 함수 생성
- [x] debug 함수 생성
