### ISSUE TITLE
[Feat] 정적 페이지 반환하는 간단한 웹서버 구현

### ISSUE THREAD

**Issue by Arkingco** [CuteWebserv/webserv#9]
## Desc
- 저정 페이지를 반환하는 간단한 웹서버 입니다

## Detail
- 소켓 프로그래밍 + 정적 페이지를 반환할 수 있도록 HTTP MESSAGE를 만들어 send 하는 예제 입니다!
- 클라이언트는 크롬이 담당하고 서버는 소켓 프로그래밍으로 구현 되어있습니다
- Socket(), bind(), listen(), accept(), send(), recv() 함수는 각각 소켓 프로그래밍 함수 입니다.
- 함수의 사용 방법은 노션에서 확인하십숑
- 나중에 파일을 받아서 보낼수 있게 개선하겠습니다!

## Todo

- [x] 소켓 프로그래밍 간단작성
- [x] 서버 소켓열고 클라이언트 요청 기다리기
- [x] 정적인 HTTP 메시지 만들어서 전달
   - [x] char[] 배열 만들어서 RESPONCE MEESAGE 한줄 씩 작성
- [x] 데이터 전달 

## Etc

해당하는 서버에 클라이언트가 연결이 된 상태로 서버를 종료하면 소켓이 정상적으로 닫아지지 않아서
bind error가 발생할 수 있습니다 주의하세요!!
